// Generated by CoffeeScript 1.6.3
/*
Module dependencies.
*/


(function() {
  var Game, app, express, game, http, io, mongoose, path, routes, server, server_io, user, user_id;

  express = require("express");

  routes = require("./routes");

  user = require("./routes/user");

  http = require("http");

  path = require("path");

  io = require('socket.io');

  global._ = require('underscore');

  mongoose = require('mongoose');

  Game = require('./src/game').Game;

  app = express();

  app.set("port", process.env.PORT || 3000);

  app.set("views", path.join(__dirname, "views"));

  app.set("view engine", "jade");

  app.use(express.favicon());

  app.use(express.logger("dev"));

  app.use(express.json());

  app.use(express.urlencoded());

  app.use(express.methodOverride());

  app.use(app.router);

  app.use(express["static"](path.join(__dirname, "public")));

  if ("development" === app.get("env")) {
    app.use(express.errorHandler());
  }

  app.get("/", routes.index);

  app.get("/users", user.list);

  server = http.createServer(app);

  server.listen(app.get('port'));

  server_io = io.listen(server);

  server_io.set('close timeout', 60);

  server_io.set('heartbeat timeout', 60);

  user_id = 0;

  game = new Game(user_id);

  game.start(server_io);

}).call(this);
